### ISSUE TITLE
0 degrees C displays as minus zero degrees C (-0°C)

### ISSUE THREAD

**Issue by davidminsky** [inderdhir/DatWeatherDoe#52]
Minor issue, but when DatWeatherDoe is running and it's 0 degrees (Celsius, haven't observed Fahrenheit ... yet), it's displayed as minus zero degrees C ( -0&deg;C )

I'm using the latest available version of DatWeatherDoe, via brew.

Here's a screenshot, to illustrate:

![Screen Shot 2021-11-17 at 10 23 47 AM](https://user-images.githubusercontent.com/94550235/142231122-bb7bfb42-01f4-4e8b-b68c-d0a038d84f9e.png)

Love DatWeatherDoe, it's useful to me!

**Comment by inderdhir** [comment]
Fixed in next release https://github.com/inderdhir/DatWeatherDoe/pull/53/, will update here when it's live ☕

**Comment by inderdhir** [comment]
Out now in 2.1.5

**Comment by davidminsky** [comment]
@inderdhir Thank you so much for taking some time and fixing this minor issue so quickly -- updated via `brew`, and it looks great. Kudos!

**Comment by grr** [comment]
still seeing this issue even on  2.2.0. it looks like it now only affects the case that the user select 'All' under Configure>Unit.
<img width="77" alt="Screen Shot 2022-01-11 at 15 29 24" src="https://user-images.githubusercontent.com/690894/149024659-be7e2885-89d6-4b0b-a46f-6a47d15008bd.png">
<img width="133" alt="Screen Shot 2022-01-11 at 15 28 56" src="https://user-images.githubusercontent.com/690894/149024680-ed3fd7f6-2422-48a7-b8f5-cb4b9bb8ad70.png">
